### ISSUE TITLE
Uncaught Promise in Script Editor

### ISSUE THREAD

**Issue by nanogyth** [bitburner-official/bitburner-src#1408]
```
UNCAUGHT PROMISE ERROR
You forgot to await a promise
maybe hack / grow / weaken ?

RUNTIME ERROR:

Unexpected usage
stack:
Error: Unexpected usage
    at v.loadForeignModule (https://bitburner-official.github.io/dist/vendor.bundle.js:155:5658530)
    at https://bitburner-official.github.io/dist/vendor.bundle.js:155:4905221
```

Latest version, 2.6.1 (d2c7b2504)
I had just opened the game and didn't have any scripts running.
This popped up every time I switched to the script editor.

Export, delete, import cleared the problem, so I can't reproduce it.
Maybe just a random cosmic ray bit flip.
Super low priority if it doesn't happen again.

**Comment by catloversg** [comment]
It's caused by `monaco-editor` (the in-game editor), but we won't be able to do anything if it's not reproducible.

**Comment by austinjones** [comment]
I found a version of this that is reproducible.  It seems to happen on any save past a point in time.  Let me know if you'd like them uploaded somewhere.

The editor is blank - no open files when this happens.
```
UNCAUGHT PROMISE ERROR
You forgot to await a promise
maybe hack / grow / weaken ?

RUNTIME ERROR:

Unexpected usage
stack:
Error: Unexpected usage
    at v.loadForeignModule (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:155:5652171)
    at file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:155:4898862
    at async file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:155:6850245
    at async h.getLanguageServiceWorker (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:155:6850338)
    at async _._doValidate (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:155:6855159)
```

**Comment by catloversg** [comment]
You should provide reproducible steps and upload your save file here.
