### ISSUE TITLE
Steam version on older linux distributions requires Proton 7.x compatibility mode

### ISSUE THREAD

**Issue by KarlHornell** [bitburner-official/bitburner-src#380]
Bitburner won't start on debian11 linux as of the 2023-02-22 update in steam.
To try and debug things I did try starting from the terminal mimicking what steam did.

See stacktrace from this terminal run below:
```
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/karl/.steam/debian-installation/steamapps/common/Bitburner/resources/app/lib/greenworks-linux64.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/karl/.steam/debian-installation/steamapps/common/Bitburner/resources/app/greenworks.js:17:43)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
[3647904:0222/080429.183504:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

**Comment by Snarling** [comment]
Got the same report on discord as well. That user reported that it loads fine in proton + windows version.

Edit: Confirmed later in the issue that Proton 7.x compatibility mode works so far for ~~all~~ some affected.

**Comment by KarlHornell** [comment]
I can add that the workaround of running the proton-version did not work for me (at least the proton versions I tried).
And building a new libstdc++ only reveals it also depends on a newer libC, which would be more or less impossible to fix without upgrading to a newer Debian release. 
Debian 12 not being released yet.

EDIT: I misslicked to close the issue...

**Comment by Snarling** [comment]
I'm not sure if or how we can force the linux version to compile without the GLIBCXX_3.4.29 prerequisite, but that seems like it would be the fix here.

**Comment by KarlHornell** [comment]
Yes, building electron against older versions than  GLIBCXX_3.4.29 and GLIBC_2.33 should be the right solution.
I'm not sure if there's more dependencies that need to be considered.

I might try to build electron myself at some point to verify that I can launch with it, at some point.

**Comment by kodingkoning** [comment]
I'm having this same problem on Ubuntu 20.04.5. Steam says Bitburner is launched, but the window doesn't open.

**Comment by Snarling** [comment]
~~I tried building the game using an ubuntu 20.04 github runner, which should have an earlier glibc version. Can one of you test if this version of the game is playable?
https://easyupload.io/8uje7q
Sorry for using some weird filesharing site, github would not let me upload a file larger than 25MB and the actual build artifact from the github workflow is only accessible by maintainers.~~ Tested and did not work. Proton 7.x compatibility mode seems to work with version on Steam.

**Comment by kodingkoning** [comment]
What do I need to do to run this? Downloaded and tried `./bitburner` and got:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-log'
Require stack:
- /home/erk24/Downloads/bitburner/resources/app/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109411)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/erk24/Downloads/bitburner/resources/app/main.js:4:13)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
[277566:0303/075818.294401:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
[277566:0303/075818.294454:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
Aborted (core dumped)
```

**Comment by Snarling** [comment]
Sorry I'm not sure, I would assume that would have been the right way to launch it. I don't currently have a test setup to try it out myself.

**Comment by roberto-mansfield** [comment]
I tested by replacing my .steam/debian-installation/steamapps/common/Bitburner directory with the files in the artifact and got the same error as kodingkoning:

`A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-log'
Require stack:
- /home/robertom/.steam/debian-installation/steamapps/common/Bitburner/resources/app/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109411)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/robertom/.steam/debian-installation/steamapps/common/Bitburner/resources/app/main.js:4:13)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
libva error: /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so has no function __vaDriverInit_1_0
[11451:0307/100131.345710:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
[11420:0307/100136.451808:ERROR:nss_util.cc(349)] After loading Root Certs, loaded==false: NSS error code: -8018`

If I copy just the bitburner executable into my original directory, I get the original `GLIBCXX_3.4.29' not found` error.

The original bitburner file and the one from the artifact are the same size and diff reports no differences.

FYI, the game does play for me if I use the Proton 7.x compatibility mode.

**Comment by KarlHornell** [comment]
> FYI, the game does play for me if I use the Proton 7.x compatibility mode.

Can confirm workaround with Proton 7.0-6

**Comment by kodingkoning** [comment]
I tried with both Proton 7.0-6 enabled and 8.0-2, but neither allows bitburner to launch.

**Comment by d0sboots** [comment]
Because no one has mentioned the obvious yet: BB is a web game. It would obviously be best if the Electron version worked in Linux, but as a workaround you can use the web version.

**Comment by Snarling** [comment]
The missing electron-log issue mentioned in this thread was due to a separate issue with a faulty electron packager script that wasn't including modules on the first time the packager script was ran (which included every time it was ran from a workflow), that part was fixed on f3c32d7.

The glibc issue is still a problem, and it is unfortunately not solved by building the game on Ubuntu 20.04 like we suspected it might be.

**Comment by KarlHornell** [comment]
Since Debian 12.0 (Bookworm) was released, together with a new version of glibc (2.36-9) , this does not seem to be an issue for me anymore. I believe 2.33 was the one required by bitburner, and it does launch properly now without proton.

Looking at the current version of major distributions it would seem that most or all use 2.37+. Of course the best thing would be to fix the building process, but I think it would not be unreasonable to encourage users to update their systems if the build process is hard to fix. That's my opinion at least.

**Comment by catloversg** [comment]
This issue will be fixed when #1563 and #2114 are merged. In order to integrate with Steam, we need to use a native module. Until v2.8.1, we use `greenworks`. This module requires glibc 2.33 and libstdc++ 3.4.29. In v3.0.0, we will switch to `steamworks.js` module which only requires glibc 2.29. This means that it's compatible with Debian 11, Ubuntu 20.04 and RHEL 9.
