### ISSUE TITLE
Recovery mode on game start

### ISSUE THREAD

**Issue by xlilos** [bitburner-official/bitburner-src#540]
- Save file: [RECOVERY_BITBURNER_1685276564.zip](https://github.com/bitburner-official/bitburner-src/files/11584553/RECOVERY_BITBURNER_1685276564.zip)
- Steps to reproduce: Load save file 
- Version of the game: v2.3.0 (037149a16)

It has been a bit since I played this game, booted it up and got this. Looking at when I got my last achievements, I was playing on v1.6.3 previously.

**Comment by xlilos** [comment]
Did a soft reset, some more issues popped up, running `cd` or `ls` gives this error: 

```UNCAUGHT PROMISE ERROR
You forgot to await a promise
maybe hack / grow / weaken ?

RUNTIME ERROR:

t.startsWith is not a function
stack:
TypeError: t.startsWith is not a function
    at h (file:///E:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1058759)
    at C (file:///E:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1366333)
    at g (file:///E:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1366533)
    at ge.executeCommand (file:///E:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1353514)
    at ge.executeCommands (file:///E:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1349870)
    at onKeyDown (file:///E:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:2:1386169)
    at Object.He (file:///E:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:155:4877150)
    at Ke (file:///E:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:155:4877304)
    at file:///E:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:155:4895482
    at Ei (file:///E:/SteamLibrary/steamapps/common/Bitburner/resources/app/dist/vendor.bundle.js:155:4895576)
```

**Comment by d0sboots** [comment]
I'll be bookmarking this one for future tests too. I'll take a look later today.

**Comment by d0sboots** [comment]
Aha! Thank you for the 2nd part of your report, someone else sent in the same thing and I couldn't figure out how they'd gotten to that state. What you said filled in the rest of the picture.

I have a fix for the 2nd part, but I should be able to fix the whole thing.

**Comment by xlilos** [comment]
Just was able to load my old save file, my scripts have not been lost to the void =) thanks!
